name: Check duplicate daily

on:
  push:
    branches:
      - "master"
    paths: 'public/daily/**'
  pull_request:
    branches:
      - "master"
    paths: 'public/daily/**'

jobs:     
  check_duplicates:
    name: Search for duplicates in daily
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: v1.x 
      - name: Deno check duplicate
        run: deno test --allow-read test/check_duplicate_daily.ts
